# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a719826996e4dd1d1640aed3c4bdd30ea5d7526fb2ddfb53d7a1f95ef2761737e28abd967920de753ad988cec622278b8c5c94e6034ec4f5d46ed892baab8055

test:
  secret_key_base: 6322ace85188f6099faf29aa7eed66f011029cc0e4a0c403df1cbf7ce9e12875251d221d6bc7e2b06210c346f2baad2ab543057f73829678b4d4f8e6d6d9d2ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
